// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebSocketGateway.Infrastructure.Data;

#nullable disable

namespace WebSocketGateway.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260625140828_AddNotificationSettings")]
    partial class AddNotificationSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wsgateway")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebSocketGateway.Domain.Entities.NotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("NotifyOnCompletion")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_completion");

                    b.Property<bool>("NotifyOnError")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_error");

                    b.Property<bool>("NotifyOnHitl")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_hitl");

                    b.Property<bool>("NotifyOnPublication")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_on_publication");

                    b.Property<bool>("NotifyOnlyWhenOffline")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_only_when_offline");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<string>("TelegramUsername")
                        .HasColumnType("text")
                        .HasColumnName("telegram_username");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_settings");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_settings_user_id");

                    b.ToTable("notification_settings", "wsgateway");
                });
#pragma warning restore 612, 618
        }
    }
}
