// <auto-generated/>
#pragma warning disable CS0618
using AiGateway.Web.Clients.MediaIngest.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item.Link
{
    /// <summary>
    /// Builds and executes requests for operations under \api\internal\media\{mediaId}\link
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LinkRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item.Link.LinkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LinkRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/internal/media/{mediaId}/link?linkType={linkType}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item.Link.LinkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LinkRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/internal/media/{mediaId}/link?linkType={linkType}", rawUrl)
        {
        }
        /// <summary>
        /// Service-to-service only. Returns a URL for the media file based on the requested link type.
        /// </summary>
        /// <returns>A <see cref="global::AiGateway.Web.Clients.MediaIngest.Models.GetLinkByIdResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::AiGateway.Web.Clients.MediaIngest.Models.ProblemDetails">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::AiGateway.Web.Clients.MediaIngest.Models.GetLinkByIdResponse?> GetAsync(Action<RequestConfiguration<global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item.Link.LinkRequestBuilder.LinkRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::AiGateway.Web.Clients.MediaIngest.Models.GetLinkByIdResponse> GetAsync(Action<RequestConfiguration<global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item.Link.LinkRequestBuilder.LinkRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::AiGateway.Web.Clients.MediaIngest.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::AiGateway.Web.Clients.MediaIngest.Models.GetLinkByIdResponse>(requestInfo, global::AiGateway.Web.Clients.MediaIngest.Models.GetLinkByIdResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Service-to-service only. Returns a URL for the media file based on the requested link type.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item.Link.LinkRequestBuilder.LinkRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item.Link.LinkRequestBuilder.LinkRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item.Link.LinkRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item.Link.LinkRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item.Link.LinkRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Service-to-service only. Returns a URL for the media file based on the requested link type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LinkRequestBuilderGetQueryParameters 
        {
            [Obsolete("This property is deprecated, use LinkTypeAsLinkType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("linkType")]
            public string? LinkType { get; set; }
#nullable restore
#else
            [QueryParameter("linkType")]
            public string LinkType { get; set; }
#endif
            [QueryParameter("linkType")]
            public global::AiGateway.Web.Clients.MediaIngest.Models.LinkType? LinkTypeAsLinkType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LinkRequestBuilderGetRequestConfiguration : RequestConfiguration<global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item.Link.LinkRequestBuilder.LinkRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
