apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  data:
  - secretKey: AMQP_URL
    remoteRef:
      key: {{ .Values.secrets.rabbitMqConnection.key }}
      {{- if .Values.secrets.rabbitMqConnection.version }}
      version: {{ .Values.secrets.rabbitMqConnection.version }}
      {{- end }}
  - secretKey: MINIO_ACCESS_KEY
    remoteRef:
      key: {{ .Values.secrets.s3AccessKey.key }}
      {{- if .Values.secrets.s3AccessKey.version }}
      version: {{ .Values.secrets.s3AccessKey.version }}
      {{- end }}
  - secretKey: MINIO_SECRET_KEY
    remoteRef:
      key: {{ .Values.secrets.s3SecretKey.key }}
      {{- if .Values.secrets.s3SecretKey.version }}
      version: {{ .Values.secrets.s3SecretKey.version }}
      {{- end }}
  - secretKey: CELERY_RESULT_BACKEND
    remoteRef:
      key: {{ .Values.secrets.celeryResultBackend.key }}
      {{- if .Values.secrets.celeryResultBackend.version }}
      version: {{ .Values.secrets.celeryResultBackend.version }}
      {{- end }}
