environment: Staging

secrets:
  litellmApiKey:
    key: test-litellm-api-key


volumeMounts:
  - name: config-volume
    mountPath: /app/appsettings.Staging.json
    subPath: appsettings_override.json

appConfig:
  MediaIngest:
    BaseUrl: "http://mediaingest.test-env.svc.cluster.local"
  OpenAi:
    BaseUrl: "http://litellm.test-env.svc.cluster.local"
    TranscriptionModel: "whisper-1"
  LiteLlm:
    BaseUrl: "http://litellm.test-env.svc.cluster.local"
