replicaCount: 1

image:
  repository: ghcr.io/akisliy/amplify/ai-gateway
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: false
  annotations: {}

service:
  type: ClusterIP
  port: 5080

livenessProbe:
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /health
    port: http

externalSecret:
  name: ai-gateway-external-secret
  refreshInterval: 1h

secret:
  name: ai-gateway-secret

# override in specific env file
appConfig: {}
