---
# Source: infra/templates/amplify-gateway.yaml
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: amplify-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - dev.amplify-vkr.example.com
    port:
      name: http
      number: 80
      protocol: HTTP

---
# Source: user-service/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  labels:
    helm.sh/chart: user-service-0.1.0
    app.kubernetes.io/name: user-service
    app.kubernetes.io/instance: userservice
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken:
---
# Source: user-service/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: userservice-config
data:
  "appsettings_override.json": |
    {
      "ConnectionStrings": {
        "UserServiceDb": "Host=host.minikube.internal;Port=6433;Database=myDb;Username=dev_user;Password=dev_password;"
      },
      "CorsOptions": {
        "AllowedOrigins": [
          "https://dev.amplify-vkr.example.com"
        ],
        "DefaultPolicyName": "DevelopmentCorsPolicy"
      },
      "ExternalUrls": {
        "MediaServiceApi": "https://media.my-prod-site.com"
      },
      "Frontend": {
        "EmailConfirmationPath": "/confirm-email",
        "EmailConfirmedPath": "/api/index.html?url=/api/specification.json",
        "PasswordResetPath": "/reset-password",
        "Url": "https://dev.amplify-vkr.example.com"
      },
      "InternalUrls": {
        "MediaServiceInternalBaseUrl": "http://media-service.default.svc.cluster.local"
      },
      "Jwt": {
        "Audience": "MyAppDevelopmentUsers",
        "Issuer": "MyAppDevelopment",
        "Key": "DevelopmentSecretKeyForJwtTokenGeneration",
        "PrivateKeyPem": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCxHFHd6PSj473m\n6JvPKT4fwcIy0PMQsjs2VudEcVKeB5NoC9KOvy1wRF//FJIx/25qwb93lsAQPqCu\ngjc9GO6ZPoYIw5zwifHjJAuouQ3AS84ehDJPwr1uHYA2vUArKQ5yq5K0qENURucO\nyfLqRg+/SI9Mki7bc1kXLzzvAnvTE7JmwxAuxmRm89gScLoCQjeOYC5+xfmIukBP\nRNrOnHb/vMt59zfnl0ibBJK32J9O+XspTB8JvqkgGD+0CDFdZdQwtq92A3vtz5Cm\n7AKc638RhCk+MDkm3sLr+aDQBONnscgJfF9a+xSKTMcO/l+wkdyL2bdxd3xaReeH\nJdS4or3NAgMBAAECggEACyurmDD4uRuEnzs9lIfX5L3eR0E5i2yKYoeBp6X0HYaB\nzBauzZUOQx305gxAmkmvh6k3r83AyGWC0e7hmAdqCR1R69yWme9BY9+iop4lWWMO\nmYsh9zjjpL3Ul99A3FgHEsFyi9VvBbJBIYQoP5FyrdBgRWaU8P9p95XhpHuGHs5s\n0yI1pRhNro2tLpn+PfrlpeGN7eJcgn2sMaDWhLI1qD/1c1EO6WDbOOOx+jgiQQqL\nsvvxZpS6eadusMytAAY3sxwbJNWNUbK2sItWHObZSuOz6erxRCP8j3zy/HEY6QUJ\nrAlPtflLkD1wQS6KDHleT9FpnEW3vkL4wFmec/n8IQKBgQDheitrPIT69MgUjrrj\nCJnhnvh/b0LyGkFhfhMQPx8H2jqL3JjndEKwgycVzbcbfri4QI+43U/nOnigjNIy\nKWTXAuhiOLHOTOaDBn4ONIB8XVuItMl/FunRcinMPjPCnLB/VWrxyYRfncS9TUP4\nQhVaXot3/ce6F8IUqfqQ9M980QKBgQDJFgX93PwXfI2yN8zzT6yCG21FARA+KJHJ\ndm4DEn6+bFpZ609/hgSCL0ftk3LlgH7lb1amfU8jG6pwSVgiZk+ZWoiUlww96ruC\nKyhk7OUhYHTg+HS+RMUeWQx23yqBrg336D9l3vEFpsOGa5+CxjBIQhH90owtZ7kt\nm1ee9JIAPQKBgD/9MutJDphF9a5X31PlMf6k5fMMeVxJ9Toc1H4s27qXxTvCDCbL\niM2dOu9mJUwJR5UKxX76V93Qa0FtFY4kzzhx289cNaHNkzGmGwoe/kPNHtgKLpEB\nyLOnCZOsJ3ZYj4JjlGkv/oBAPwBWOC7xWiv+Xuhbvl3itjK1FqYiw+uxAoGACZKy\n1lMe7T9Qv5tIdozkeY00toRGca8cwaqRsjO/NPGTm5RIRJnsvQXjNrw+TA7B+8pB\nJcvxaIp4or/bIkgcogBdYDWQr6HtK1VCpwtgHSaqactqQ2Sivb8fiMk3DNVsdNDp\ns7/ZWZuG029sOJ2WztnWYW8UnVTCzBkJItgh20ECgYBHaZNUtjOaqOHjyVOqOyw7\nj4lXbox+fgnMkVelalpLv+bQXUd16hcU5ztg6+fo6VPiT1lObCZcNobZomXII2mU\nOJVnOuWcCWPAv1yYAsByPhG8nLmc1dS8yPj/Nxn+6agV0gcvQlWlSokWHcjJOyO7\nVRADnOB2UEfUN7Q7dDLWbA==\n-----END PRIVATE KEY-----"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning"
        }
      },
      "MailOptions": {
        "ApiKey": "re_QHKsUPYD_A5wfib9HrizZxRz7NJ85C2Ed"
      },
      "MyCookies": {
        "AccessTokenCookieName": "MyAppAccessToken",
        "RefreshTokenCookieName": "MyAppRefreshToken"
      }
    }
---
# Source: user-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: userservice-user-service
  labels:
    helm.sh/chart: user-service-0.1.0
    app.kubernetes.io/name: user-service
    app.kubernetes.io/instance: userservice
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/instance: userservice
---
# Source: user-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-user-service
  labels:
    helm.sh/chart: user-service-0.1.0
    app.kubernetes.io/name: user-service
    app.kubernetes.io/instance: userservice
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
      app.kubernetes.io/instance: userservice
  template:
    metadata:
      labels:
        helm.sh/chart: user-service-0.1.0
        app.kubernetes.io/name: user-service
        app.kubernetes.io/instance: userservice
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: user-service-sa
      containers:
        - name: user-service
          image: "akisliy/amplify-userservice:0.1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_HTTP_PORTS
              value: "80"
          volumeMounts:
            - mountPath: /app/appsettings.Development.json
              name: config-volume
              subPath: appsettings_override.json
      volumes:
        - configMap:
            name: userservice-config
          name: config-volume
---
# Source: user-service/templates/virtualservice.yaml
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: muffin-currency-internal-vs
spec:
  hosts:
  - "dev.amplify-vkr.example.com"
  # intenral service communication
  - "userservice-user-service.amplify.svc.cluster.local"
  gateways:
  - amplify-gateway
  http:
  - match:
    - uri:
        prefix: "/api/auth"
    route:
    - destination:
        host: "userservice-user-service"
        port:
          number: 80
    timeout: 2s
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: gateway-error,connect-failure,refused-stream,5xx

