environments:
  default:
    values:
      - infra/globals/values.yaml 
  dev:
    values:
      - infra/globals/values.dev.yaml
  prod:
    values:
      - infra/globals/values.prod.yaml
---
releases:
  - name: gateway
    chart: ./infra/
    labels:
      tier: infra
    values:
      - ./infra/envs/values.yaml.gotmpl
      - ./infra/envs/values.{{ .Environment.Name }}.yaml

  - name: userservice
    chart: ./userservice/charts
    labels:
      tier: backend
      app: userservice
    values:
      - ./userservice/charts/envs/values.yaml
      - ./userservice/charts/envs/values.yaml.gotmpl
      - ./userservice/charts/envs/values.{{ .Environment.Name }}.yaml
    needs:
      - gateway
  
  - name: publisher
    chart: ./publisher/charts
    labels:
      tier: backend
      app: publisher
    values:
      - ./publisher/charts/envs/values.yaml
      - ./publisher/charts/envs/values.yaml.gotmpl
      - ./publisher/charts/envs/values.{{ .Environment.Name }}.yaml
    needs:
      - gateway
    
  - name: mediaingest
    chart: ./media-ingest/charts
    labels:
      tier: backend
      app: media-ingest
    values:
      - ./media-ingest/charts/envs/values.yaml
      - ./media-ingest/charts/envs/values.yaml.gotmpl
      - ./media-ingest/charts/envs/values.{{ .Environment.Name }}.yaml
    needs:
      - gateway
    