environments:
  default:
    values:
      - infra/globals/values.yaml
  stage:
    values:
      - infra/globals/values.stage.yaml
      - namespace: test-env
  prod:
    values:
      - infra/globals/values.prod.yaml
  dev:
    values:
      - infra/globals/values.dev.yaml
      - namespace: amplify-dev
---
repositories:
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: litellm
    url: docker.litellm.ai/berriai
    oci: true
  - name: kiali
    url: https://kiali.org/helm-charts
  - name: temporal
    url: https://go.temporal.io/helm-charts
releases:
  - name: kiali-server
    condition: kiali.enabled
    namespace: istio-system
    chart: kiali/kiali-server
    createNamespace: true
    labels:
      tier: infra
    values:
      - ./infra/kiali/values.yaml
      - ./infra/kiali/values.{{ .Environment.Name }}.yaml

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    createNamespace: true
    labels:
      tier: infra
    set:
      - name: installCRDs
        value: true
      - name: global.leaderElection.namespace
        value: cert-manager
      - name: extraArgs[0]
        value: "--issuer-ambient-credentials=true"

  - name: otel-operator
    namespace: opentelemetry-operator-system
    chart: open-telemetry/opentelemetry-operator
    createNamespace: true
    labels:
      tier: infra
    set:
      - name: manager.collectorImage.repository
        value: otel/opentelemetry-collector-contrib
    needs:
      - cert-manager/cert-manager

  - name: gateway
    namespace: "{{ .Values.namespace }}"
    chart: ./infra/
    labels:
      tier: infra
    values:
      - ./infra/envs/values.yaml.gotmpl
      - ./infra/envs/values.{{ .Environment.Name }}.yaml

  - name: litellm
    namespace: "{{ .Values.namespace }}"
    chart: litellm/litellm-helm
    labels:
      tier: backend
      app: litellm
    values:
      - ./litellm/values.yaml
      - ./litellm/values.{{ .Environment.Name }}.yaml

  - name: temporal-extras
    namespace: temporal
    chart: ./temporal/extras
    createNamespace: true
    labels:
      tier: infra
      app: temporal
    values:
      - ./temporal/extras/envs/values.{{ .Environment.Name }}.yaml

  - name: temporal
    namespace: temporal
    chart: temporal/temporal
    labels:
      tier: infra
      app: temporal
    values:
      - ./temporal/values.yaml
    needs:
      - temporal/temporal-extras

  - name: userservice
    namespace: "{{ .Values.namespace }}"
    chart: ./userservice/charts
    labels:
      tier: backend
      app: userservice
    wait: true
    waitForJobs: true
    timeout: 300
    values:
      - ./userservice/charts/envs/values.yaml
      - ./userservice/charts/envs/values.yaml.gotmpl
      - ./userservice/charts/envs/values.{{ .Environment.Name }}.yaml
    needs:
      - gateway

  - name: publisher
    namespace: "{{ .Values.namespace }}"
    chart: ./publisher/charts
    labels:
      tier: backend
      app: publisher
    wait: true
    waitForJobs: true
    timeout: 300
    values:
      - ./publisher/charts/envs/values.yaml
      - ./publisher/charts/envs/values.yaml.gotmpl
      - ./publisher/charts/envs/values.{{ .Environment.Name }}.yaml
    needs:
      - gateway

  - name: mediaingest
    namespace: "{{ .Values.namespace }}"
    chart: ./media-ingest/charts
    labels:
      tier: backend
      app: media-ingest
    wait: true
    waitForJobs: true
    timeout: 300
    values:
      - ./media-ingest/charts/envs/values.yaml
      - ./media-ingest/charts/envs/values.yaml.gotmpl
      - ./media-ingest/charts/envs/values.{{ .Environment.Name }}.yaml
    needs:
      - gateway

  - name: ws-gateway
    namespace: "{{ .Values.namespace }}"
    chart: ./websocket-gateway/charts
    labels:
      tier: backend
      app: ws-gateway
    wait: true
    timeout: 300
    values:
      - ./websocket-gateway/charts/envs/values.yaml
      - ./websocket-gateway/charts/envs/values.yaml.gotmpl
      - ./websocket-gateway/charts/envs/values.{{ .Environment.Name }}.yaml
    needs:
      - gateway

  - name: video-editor
    namespace: "{{ .Values.namespace }}"
    chart: ./video-editor/charts
    labels:
      tier: backend
      app: video-editor
    wait: true
    timeout: 300
    values:
      - ./video-editor/charts/envs/values.yaml
      - ./video-editor/charts/envs/values.yaml.gotmpl
      - ./video-editor/charts/envs/values.{{ .Environment.Name }}.yaml
    needs:
      - gateway

  - name: ai-gateway
    namespace: "{{ .Values.namespace }}"
    chart: ./ai-gateway/charts
    labels:
      tier: backend
      app: ai-gateway
    wait: true
    timeout: 300
    values:
      - ./ai-gateway/charts/envs/values.yaml
      - ./ai-gateway/charts/envs/values.yaml.gotmpl
      - ./ai-gateway/charts/envs/values.{{ .Environment.Name }}.yaml
    needs:
      - gateway

  - name: template-service
    namespace: "{{ .Values.namespace }}"
    chart: ./template-service/charts
    labels:
      tier: backend
      app: template-service
    wait: true
    timeout: 300
    values:
      - ./template-service/charts/envs/values.yaml
      - ./template-service/charts/envs/values.yaml.gotmpl
      - ./template-service/charts/envs/values.{{ .Environment.Name }}.yaml
    needs:
      - gateway
