environments:
  default:
    values:
      - infra/globals/values.yaml
  stage:
    values:
      - infra/globals/values.stage.yaml
      - namespace: test-env
  prod:
    values:
      - infra/globals/values.prod.yaml
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: gateway
    namespace: "{{ .Values.namespace }}"
    chart: ./infra/
    labels:
      tier: infra
    values:
      - ./infra/envs/values.yaml.gotmpl
      - ./infra/envs/values.{{ .Environment.Name }}.yaml

  - name: userservice
    namespace: "{{ .Values.namespace }}"
    chart: ./userservice/charts
    labels:
      tier: backend
      app: userservice
    values:
      - ./userservice/charts/envs/values.yaml
      - ./userservice/charts/envs/values.yaml.gotmpl
      - ./userservice/charts/envs/values.{{ .Environment.Name }}.yaml
    needs:
      - gateway

  - name: publisher
    namespace: "{{ .Values.namespace }}"
    chart: ./publisher/charts
    labels:
      tier: backend
      app: publisher
    values:
      - ./publisher/charts/envs/values.yaml
      - ./publisher/charts/envs/values.yaml.gotmpl
      - ./publisher/charts/envs/values.{{ .Environment.Name }}.yaml
    needs:
      - gateway

  - name: postgres
    namespace: test-env
    chart: bitnami/postgresql
    version: 15.0.0
    labels:
      tier: infra
    values:
      - auth:
          postgresPassword: "superSecretPassword123"
          username: "app_user"
          password: "app_password"
          database: "amplify_db"
      - architecture: standalone
      - primary:
          persistence:
            enabled: true
            size: 8Gi
      - image:
          tag: latest

  - name: mediaingest
    namespace: "{{ .Values.namespace }}"
    chart: ./media-ingest/charts
    labels:
      tier: backend
      app: media-ingest
    values:
      - ./media-ingest/charts/envs/values.yaml
      - ./media-ingest/charts/envs/values.yaml.gotmpl
      - ./media-ingest/charts/envs/values.{{ .Environment.Name }}.yaml
    needs:
      - gateway
