// <auto-generated/>
#pragma warning disable CS0618
using AiGateway.Web.Clients.ElevenLabs.V1.SpeechToSpeech.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AiGateway.Web.Clients.ElevenLabs.V1.SpeechToSpeech
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\speech-to-speech
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SpeechToSpeechRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the AiGateway.Web.Clients.ElevenLabs.v1.speechToSpeech.item collection</summary>
        /// <param name="position">Voice ID to be used, you can use https://api.elevenlabs.io/v1/voices to list all the available voices.</param>
        /// <returns>A <see cref="global::AiGateway.Web.Clients.ElevenLabs.V1.SpeechToSpeech.Item.WithVoice_ItemRequestBuilder"/></returns>
        public global::AiGateway.Web.Clients.ElevenLabs.V1.SpeechToSpeech.Item.WithVoice_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("voice_id", position);
                return new global::AiGateway.Web.Clients.ElevenLabs.V1.SpeechToSpeech.Item.WithVoice_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AiGateway.Web.Clients.ElevenLabs.V1.SpeechToSpeech.SpeechToSpeechRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SpeechToSpeechRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/speech-to-speech", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AiGateway.Web.Clients.ElevenLabs.V1.SpeechToSpeech.SpeechToSpeechRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SpeechToSpeechRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/speech-to-speech", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
