// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AiGateway.Web.Clients.MediaIngest.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum LinkType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "GoogleCloudStorage")]
        #pragma warning disable CS1591
        GoogleCloudStorage,
        #pragma warning restore CS1591
        [EnumMember(Value = "Public")]
        #pragma warning disable CS1591
        Public,
        #pragma warning restore CS1591
        [EnumMember(Value = "Presigned")]
        #pragma warning disable CS1591
        Presigned,
        #pragma warning restore CS1591
    }
}
