replicaCount: 1

image:
  repository: ghcr.io/akisliy/amplify/video-editor
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: "video-editor-sa"

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi

minio:
  host: ""
  bucket: ""
  useSsl: "false"
  location: "us-east-1"

worker:
  replicaCount: 1
  concurrency: 1
  mediaSavingPath: "/tmp/video-editor"
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "4"
      memory: 8Gi
  keda:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    queueName: "celery"       # Celery default queue name в RabbitMQ
    targetQueueLength: "3"    # 1 новый под на каждые 3 задачи в очереди

# определяется в файлах окружения
secret:
  name: ""

externalSecret:
  name: video-editor-external-secret
  refreshInterval: 1h

service:
  type: ClusterIP
  port: 8000

internalServices:
  mediaIngest:
    url: "http://media-service.default.svc.cluster.local/media"

secrets:
  rabbitMqConnection:
    key: ""
  s3AccessKey:
    key: ""
  s3SecretKey:
    key: ""
