// <auto-generated/>
#pragma warning disable CS0618
using AiGateway.Web.Clients.MediaIngest.Api.Media.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AiGateway.Web.Clients.MediaIngest.Api.Media
{
    /// <summary>
    /// Builds and executes requests for operations under \api\media
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MediaRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the AiGateway.Web.Clients.MediaIngest.api.media.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AiGateway.Web.Clients.MediaIngest.Api.Media.Item.WithMediaItemRequestBuilder"/></returns>
        public global::AiGateway.Web.Clients.MediaIngest.Api.Media.Item.WithMediaItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("mediaId", position);
                return new global::AiGateway.Web.Clients.MediaIngest.Api.Media.Item.WithMediaItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AiGateway.Web.Clients.MediaIngest.Api.Media.MediaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MediaRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/media", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AiGateway.Web.Clients.MediaIngest.Api.Media.MediaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MediaRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/media", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
