// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Publisher.Core.Enums;
using Publisher.Infrastructure.Data;

#nullable disable

namespace Publisher.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PublisherDbContext))]
    [Migration("20250831144320_ChangeFileUrlToFileKey")]
    partial class ChangeFileUrlToFileKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "publication_status", new[] { "failed", "published", "scheduled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "social_media", new[] { "instagram", "tik_tok", "youtube" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "video_format", new[] { "AI-UGC", "Luxury edit" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoListSocialMediaAccount", b =>
                {
                    b.Property<Guid>("AccountsId")
                        .HasColumnType("uuid")
                        .HasColumnName("accounts_id");

                    b.Property<Guid>("AutoListsId")
                        .HasColumnType("uuid")
                        .HasColumnName("auto_lists_id");

                    b.HasKey("AccountsId", "AutoListsId")
                        .HasName("pk_auto_list_social_media_account");

                    b.HasIndex("AutoListsId")
                        .HasDatabaseName("ix_auto_list_social_media_account_auto_lists_id");

                    b.ToTable("auto_list_social_media_account", (string)null);
                });

            modelBuilder.Entity("Publisher.Core.Entities.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_actors");

                    b.ToTable("actors", (string)null);
                });

            modelBuilder.Entity("Publisher.Core.Entities.AutoList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PostContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_container_id");

                    b.HasKey("Id")
                        .HasName("pk_auto_lists");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_auto_lists_actor_id");

                    b.HasIndex("PostContainerId")
                        .HasDatabaseName("ix_auto_lists_post_container_id");

                    b.ToTable("auto_lists", (string)null);
                });

            modelBuilder.Entity("Publisher.Core.Entities.AutoListEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AutoListId")
                        .HasColumnType("uuid")
                        .HasColumnName("auto_list_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_weeks");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<TimeOnly>("PublicationTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("publication_time");

                    b.HasKey("Id")
                        .HasName("pk_auto_list_entries");

                    b.HasIndex("AutoListId")
                        .HasDatabaseName("ix_auto_list_entries_auto_list_id");

                    b.ToTable("auto_list_entries", (string)null);
                });

            modelBuilder.Entity("Publisher.Core.Entities.Cover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.HasKey("Id")
                        .HasName("pk_covers");

                    b.ToTable("covers", (string)null);
                });

            modelBuilder.Entity("Publisher.Core.Entities.CreatedPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverFileKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cover_file_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_key");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("PostContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_container_id");

                    b.HasKey("Id")
                        .HasName("pk_created_posts");

                    b.ToTable("created_posts", (string)null);
                });

            modelBuilder.Entity("Publisher.Core.Entities.InstagramPublishingPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AutoListId")
                        .HasColumnType("uuid")
                        .HasColumnName("auto_list_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<bool>("ShareToFeed")
                        .HasColumnType("boolean")
                        .HasColumnName("share_to_feed");

                    b.HasKey("Id")
                        .HasName("pk_instagram_publishing_presets");

                    b.HasIndex("AutoListId")
                        .IsUnique()
                        .HasDatabaseName("ix_instagram_publishing_presets_auto_list_id");

                    b.ToTable("instagram_publishing_presets", (string)null);
                });

            modelBuilder.Entity("Publisher.Core.Entities.PostContainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("LastPublishedPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_published_post_id");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.HasKey("Id")
                        .HasName("pk_post_containers");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_post_containers_actor_id");

                    b.HasIndex("LastPublishedPostId")
                        .IsUnique()
                        .HasDatabaseName("ix_post_containers_last_published_post_id");

                    b.ToTable("post_containers", (string)null);
                });

            modelBuilder.Entity("Publisher.Core.Entities.PublishedVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedVideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_video_id");

                    b.Property<string>("LinkText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link_text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<SocialMedia>("SocialMedia")
                        .HasColumnType("social_media")
                        .HasColumnName("social_media");

                    b.Property<PublicationStatus>("Status")
                        .HasColumnType("publication_status")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_published_videos");

                    b.ToTable("published_videos", (string)null);
                });

            modelBuilder.Entity("Publisher.Core.Entities.SocialMediaAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_user_id");

                    b.Property<SocialMedia>("SocialMedia")
                        .HasColumnType("social_media")
                        .HasColumnName("social_media");

                    b.HasKey("Id")
                        .HasName("pk_social_media_accounts");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_social_media_accounts_actor_id");

                    b.ToTable("social_media_accounts", (string)null);
                });

            modelBuilder.Entity("AutoListSocialMediaAccount", b =>
                {
                    b.HasOne("Publisher.Core.Entities.SocialMediaAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auto_list_social_media_account_social_media_accounts_accoun");

                    b.HasOne("Publisher.Core.Entities.AutoList", null)
                        .WithMany()
                        .HasForeignKey("AutoListsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auto_list_social_media_account_auto_lists_auto_lists_id");
                });

            modelBuilder.Entity("Publisher.Core.Entities.AutoList", b =>
                {
                    b.HasOne("Publisher.Core.Entities.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auto_lists_actors_actor_id");

                    b.HasOne("Publisher.Core.Entities.PostContainer", "PostContainer")
                        .WithMany()
                        .HasForeignKey("PostContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auto_lists_post_containers_post_container_id");

                    b.Navigation("Actor");

                    b.Navigation("PostContainer");
                });

            modelBuilder.Entity("Publisher.Core.Entities.AutoListEntry", b =>
                {
                    b.HasOne("Publisher.Core.Entities.AutoList", "AutoList")
                        .WithMany("Entries")
                        .HasForeignKey("AutoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auto_list_entries_auto_lists_auto_list_id");

                    b.Navigation("AutoList");
                });

            modelBuilder.Entity("Publisher.Core.Entities.InstagramPublishingPreset", b =>
                {
                    b.HasOne("Publisher.Core.Entities.AutoList", "AutoList")
                        .WithOne("InstagramPreset")
                        .HasForeignKey("Publisher.Core.Entities.InstagramPublishingPreset", "AutoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instagram_publishing_presets_auto_lists_auto_list_id");

                    b.Navigation("AutoList");
                });

            modelBuilder.Entity("Publisher.Core.Entities.PostContainer", b =>
                {
                    b.HasOne("Publisher.Core.Entities.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_containers_actors_actor_id");

                    b.HasOne("Publisher.Core.Entities.CreatedPost", "LastPublishedPost")
                        .WithOne("PostContainer")
                        .HasForeignKey("Publisher.Core.Entities.PostContainer", "LastPublishedPostId")
                        .HasConstraintName("fk_post_containers_created_posts_last_published_post_id");

                    b.Navigation("Actor");

                    b.Navigation("LastPublishedPost");
                });

            modelBuilder.Entity("Publisher.Core.Entities.SocialMediaAccount", b =>
                {
                    b.HasOne("Publisher.Core.Entities.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_media_accounts_actors_actor_id");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Publisher.Core.Entities.AutoList", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("InstagramPreset");
                });

            modelBuilder.Entity("Publisher.Core.Entities.CreatedPost", b =>
                {
                    b.Navigation("PostContainer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
