/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { IStreamResult, Subject } from '@microsoft/signalr';

export type IClientReceiver = {
    /**
    * @param publicationRecordId Transpiled from System.Guid
    * @param status Transpiled from string
    * @param publicUrl Transpiled from string?
    * @param error Transpiled from string?
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    onPublicationStatusChanged(publicationRecordId: string, status: string, publicUrl: string, error: string): Promise<void>;
}

