environment: Staging

secrets:
  defaultConnectionString:
    key: publisher-db-conn-test
  hangfireConnectionString:
    key: publisher-hangfire-db-conn-test
  rabbitMqConnection:
    key: rabbitmq-test
  tikTokClientKey:
    key: tiktok-client-key-sandbox
  tikTokClientSecret:
    key: tiktok-client-secret-sandbox
  instagramAppId:
    key: instagram-app-id
  instagramAppSecret:
    key: instagram-app-secret

volumeMounts:
  - name: config-volume
    mountPath: /app/appsettings.Staging.json
    subPath: appsettings_override.json

appConfig:
  Logging:
    LogLevel:
      Default: "Information"
      Microsoft: "Warning"
      Microsoft.Hosting.Lifetime: "Information"
  InstagramApiOptions:
    AppId: ""
    AppSecret: ""
    RedirectUri: "https://staging.alexeykiselev.tech/facebook/callback"
    ApiVersion: "v22.0"
    DailyLimit: 200
    BaseGraphHostUrl: "https://graph.facebook.com/"
  RabbitMQ:
    Url: ""
  ExternalUrls:
    MediaServiceApi: "http://mediaingest.test-env.svc.cluster.local/media/api/"
  Jwt:
    Issuer: "http://userservice.test-env.svc.cluster.local/userservice/api/auth"
    Audience: "MyAppDevelopmentUsers"
  PublisherOptions:
    BasePath: /publisher
  CorsOptions:
    AllowedOrigins:
      - "http://localhost:3000"
    DefaultPolicyName: DevelopmentCorsPolicy
  Frontend:
    BaseUrl: "http://localhost:3000"
    ConnectionsPath: "/connections"
  TikTokApi:
    ClientKey: ""
    ClientSecret: ""
    RedirectUri: "http://amplify.34.40.73.43.nip.io/userservice/api"