// <auto-generated/>
#pragma warning disable CS0618
using AiGateway.Web.Clients.MediaIngest.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.PresignedUpload
{
    /// <summary>
    /// Builds and executes requests for operations under \api\internal\media\presigned-upload
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PresignedUploadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.PresignedUpload.PresignedUploadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PresignedUploadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/internal/media/presigned-upload", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.PresignedUpload.PresignedUploadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PresignedUploadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/internal/media/presigned-upload", rawUrl)
        {
        }
        /// <summary>
        /// Service-to-service only. Registers a new media record and returns a presigned PUT URL for direct S3 upload.
        /// </summary>
        /// <returns>A <see cref="global::AiGateway.Web.Clients.MediaIngest.Models.CreateUploadPresignedUrlDto"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::AiGateway.Web.Clients.MediaIngest.Models.CreateUploadPresignedUrlDto?> PostAsync(global::AiGateway.Web.Clients.MediaIngest.Models.CreateUploadPresignedUrlCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::AiGateway.Web.Clients.MediaIngest.Models.CreateUploadPresignedUrlDto> PostAsync(global::AiGateway.Web.Clients.MediaIngest.Models.CreateUploadPresignedUrlCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::AiGateway.Web.Clients.MediaIngest.Models.CreateUploadPresignedUrlDto>(requestInfo, global::AiGateway.Web.Clients.MediaIngest.Models.CreateUploadPresignedUrlDto.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Service-to-service only. Registers a new media record and returns a presigned PUT URL for direct S3 upload.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::AiGateway.Web.Clients.MediaIngest.Models.CreateUploadPresignedUrlCommand body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::AiGateway.Web.Clients.MediaIngest.Models.CreateUploadPresignedUrlCommand body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.PresignedUpload.PresignedUploadRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.PresignedUpload.PresignedUploadRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.PresignedUpload.PresignedUploadRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PresignedUploadRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
