// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Publisher.Domain.Enums;
using Publisher.Infrastructure.Data;

#nullable disable

namespace Publisher.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260227134821_AddProcessedFieldToMediaPost")]
    partial class AddProcessedFieldToMediaPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("publisher")
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "publisher", "publication_status", new[] { "failed", "none", "processing", "published", "scheduled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "publisher", "social_provider", new[] { "instagram", "tik_tok", "youtube" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoListSocialAccount", b =>
                {
                    b.Property<Guid>("AccountsId")
                        .HasColumnType("uuid")
                        .HasColumnName("accounts_id");

                    b.Property<Guid>("AutoListsId")
                        .HasColumnType("uuid")
                        .HasColumnName("auto_lists_id");

                    b.HasKey("AccountsId", "AutoListsId")
                        .HasName("pk_auto_list_social_account");

                    b.HasIndex("AutoListsId")
                        .HasDatabaseName("ix_auto_list_social_account_auto_lists_id");

                    b.ToTable("auto_list_social_account", "publisher");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", "publisher");
                });

            modelBuilder.Entity("Publisher.Domain.Entities.AutoList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_auto_lists");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_auto_lists_project_id");

                    b.ToTable("auto_lists", "publisher");
                });

            modelBuilder.Entity("Publisher.Domain.Entities.AutoListEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AutoListId")
                        .HasColumnType("uuid")
                        .HasColumnName("auto_list_id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("DayOfWeeks")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_weeks");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<TimeOnly>("PublicationTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("publication_time");

                    b.HasKey("Id")
                        .HasName("pk_auto_list_entries");

                    b.HasIndex("AutoListId")
                        .HasDatabaseName("ix_auto_list_entries_auto_list_id");

                    b.ToTable("auto_list_entries", "publisher");
                });

            modelBuilder.Entity("Publisher.Domain.Entities.MediaPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AutoListId")
                        .HasColumnType("uuid")
                        .HasColumnName("auto_list_id");

                    b.Property<Guid?>("CoverMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_media_id");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<bool>("ProcessedInAutoList")
                        .HasColumnType("boolean")
                        .HasColumnName("processed_in_auto_list");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("PublicationType")
                        .HasColumnType("integer")
                        .HasColumnName("publication_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_media_posts");

                    b.HasIndex("AutoListId")
                        .HasDatabaseName("ix_media_posts_auto_list_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_media_posts_project_id");

                    b.ToTable("media_posts", "publisher");
                });

            modelBuilder.Entity("Publisher.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", "publisher");
                });

            modelBuilder.Entity("Publisher.Domain.Entities.PublicationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CommentsCount")
                        .HasColumnType("integer")
                        .HasColumnName("comments_count");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ExternalPostId")
                        .HasColumnType("text")
                        .HasColumnName("external_post_id");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("LikesCount")
                        .HasColumnType("integer")
                        .HasColumnName("likes_count");

                    b.Property<Guid>("MediaPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_post_id");

                    b.Property<SocialProvider>("Provider")
                        .HasColumnType("publisher.social_provider")
                        .HasColumnName("provider");

                    b.Property<string>("PublicUrl")
                        .HasColumnType("text")
                        .HasColumnName("public_url");

                    b.Property<string>("PublicationErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("publication_error_message");

                    b.Property<string>("RawStatsJson")
                        .HasColumnType("text")
                        .HasColumnName("raw_stats_json");

                    b.Property<int>("SharesCount")
                        .HasColumnType("integer")
                        .HasColumnName("shares_count");

                    b.Property<Guid>("SocialAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("social_account_id");

                    b.Property<DateTime?>("StatsUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stats_updated_at");

                    b.Property<PublicationStatus>("Status")
                        .HasColumnType("publisher.publication_status")
                        .HasColumnName("status");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("integer")
                        .HasColumnName("views_count");

                    b.HasKey("Id")
                        .HasName("pk_publication_records");

                    b.HasIndex("MediaPostId")
                        .HasDatabaseName("ix_publication_records_media_post_id");

                    b.HasIndex("SocialAccountId")
                        .HasDatabaseName("ix_publication_records_social_account_id");

                    b.ToTable("publication_records", "publisher");
                });

            modelBuilder.Entity("Publisher.Domain.Entities.SocialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Credentials")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("credentials");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<SocialProvider>("Provider")
                        .HasColumnType("publisher.social_provider")
                        .HasColumnName("provider");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_social_accounts");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_social_accounts_project_id");

                    b.ToTable("social_accounts", "publisher");
                });

            modelBuilder.Entity("AutoListSocialAccount", b =>
                {
                    b.HasOne("Publisher.Domain.Entities.SocialAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auto_list_social_account_social_accounts_accounts_id");

                    b.HasOne("Publisher.Domain.Entities.AutoList", null)
                        .WithMany()
                        .HasForeignKey("AutoListsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auto_list_social_account_auto_lists_auto_lists_id");
                });

            modelBuilder.Entity("Publisher.Domain.Entities.AutoList", b =>
                {
                    b.HasOne("Publisher.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auto_lists_projects_project_id");

                    b.OwnsOne("Publisher.Domain.Entities.PublicationSetup.PublicationSettings", "PublicationSettings", b1 =>
                        {
                            b1.Property<Guid>("AutoListId")
                                .HasColumnType("uuid");

                            b1.HasKey("AutoListId")
                                .HasName("pk_auto_lists");

                            b1.ToTable("auto_lists", "publisher");

                            b1.ToJson("publication_settings");

                            b1.WithOwner()
                                .HasForeignKey("AutoListId")
                                .HasConstraintName("fk_auto_lists_auto_lists_auto_list_id");

                            b1.OwnsOne("Publisher.Domain.Entities.PublicationSetup.InstagramSettings", "Instagram", b2 =>
                                {
                                    b2.Property<Guid>("PublicationSettingsAutoListId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("DisableComments")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("ShareToFeed")
                                        .HasColumnType("boolean");

                                    b2.HasKey("PublicationSettingsAutoListId");

                                    b2.ToTable("auto_lists", "publisher");

                                    b2.ToJson("publication_settings");

                                    b2.WithOwner()
                                        .HasForeignKey("PublicationSettingsAutoListId")
                                        .HasConstraintName("fk_auto_lists_auto_lists_publication_settings_auto_list_id");
                                });

                            b1.Navigation("Instagram");
                        });

                    b.Navigation("Project");

                    b.Navigation("PublicationSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("Publisher.Domain.Entities.AutoListEntry", b =>
                {
                    b.HasOne("Publisher.Domain.Entities.AutoList", "AutoList")
                        .WithMany("Entries")
                        .HasForeignKey("AutoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auto_list_entries_auto_lists_auto_list_id");

                    b.Navigation("AutoList");
                });

            modelBuilder.Entity("Publisher.Domain.Entities.MediaPost", b =>
                {
                    b.HasOne("Publisher.Domain.Entities.AutoList", "AutoList")
                        .WithMany()
                        .HasForeignKey("AutoListId")
                        .HasConstraintName("fk_media_posts_auto_lists_auto_list_id");

                    b.HasOne("Publisher.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_posts_projects_project_id");

                    b.OwnsOne("Publisher.Domain.Entities.PublicationSetup.PublicationSettings", "PublicationSettings", b1 =>
                        {
                            b1.Property<Guid>("MediaPostId")
                                .HasColumnType("uuid");

                            b1.HasKey("MediaPostId");

                            b1.ToTable("media_posts", "publisher");

                            b1.ToJson("publication_settings");

                            b1.WithOwner()
                                .HasForeignKey("MediaPostId")
                                .HasConstraintName("fk_media_posts_media_posts_id");

                            b1.OwnsOne("Publisher.Domain.Entities.PublicationSetup.InstagramSettings", "Instagram", b2 =>
                                {
                                    b2.Property<Guid>("PublicationSettingsMediaPostId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("DisableComments")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("ShareToFeed")
                                        .HasColumnType("boolean");

                                    b2.HasKey("PublicationSettingsMediaPostId");

                                    b2.ToTable("media_posts", "publisher");

                                    b2.ToJson("publication_settings");

                                    b2.WithOwner()
                                        .HasForeignKey("PublicationSettingsMediaPostId")
                                        .HasConstraintName("fk_media_posts_media_posts_publication_settings_media_post_id");
                                });

                            b1.Navigation("Instagram");
                        });

                    b.Navigation("AutoList");

                    b.Navigation("Project");

                    b.Navigation("PublicationSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("Publisher.Domain.Entities.PublicationRecord", b =>
                {
                    b.HasOne("Publisher.Domain.Entities.MediaPost", "MediaPost")
                        .WithMany("PublicationRecords")
                        .HasForeignKey("MediaPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_publication_records_media_posts_media_post_id");

                    b.HasOne("Publisher.Domain.Entities.SocialAccount", "SocialAccount")
                        .WithMany()
                        .HasForeignKey("SocialAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_publication_records_social_accounts_social_account_id");

                    b.Navigation("MediaPost");

                    b.Navigation("SocialAccount");
                });

            modelBuilder.Entity("Publisher.Domain.Entities.SocialAccount", b =>
                {
                    b.HasOne("Publisher.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_social_accounts_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Publisher.Domain.Entities.AutoList", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Publisher.Domain.Entities.MediaPost", b =>
                {
                    b.Navigation("PublicationRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
