apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}          
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secretStore.name }}           
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  data:
  - secretKey: ConnectionStrings__WsGatewayDb
    remoteRef:
      key: {{ .Values.secrets.dbConnectionString.key }}
      {{- if .Values.secrets.dbConnectionString.version }}
      version: {{ .Values.secrets.dbConnectionString.version }}
      {{- end}}
  - secretKey: RabbitMQ__Url
    remoteRef:
      key: {{ .Values.secrets.rabbitMqConnection.key }}
      {{- if .Values.secrets.rabbitMqConnection.version }}
      version: {{ .Values.secrets.rabbitMqConnection.version }}
      {{- end}}
  - secretKey: Telegram__BotToken
    remoteRef:
      key: {{ .Values.secrets.telegram.botToken.key }}
      {{- if .Values.secrets.telegram.botToken.version }}
      version: {{ .Values.secrets.telegram.botToken.version }}
      {{- end}}
  - secretKey: Telegram__WebhookUrl
    remoteRef:
      key: {{ .Values.secrets.telegram.webhookUrl.key }}
      {{- if .Values.secrets.telegram.webhookUrl.version }}
      version: {{ .Values.secrets.telegram.webhookUrl.version }}
      {{- end}}
  - secretKey: Telegram__BotUsername
    remoteRef:
      key: {{ .Values.secrets.telegram.botUsername.key }}
      {{- if .Values.secrets.telegram.botUsername.version }}
      version: {{ .Values.secrets.telegram.botUsername.version }}
      {{- end}}