apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: {{ .Values.secret.name }}
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_DSN
    remoteRef:
      key: {{ .Values.secrets.postgresDsn.key }}
      {{- if .Values.secrets.postgresDsn.version }}
      version: {{ .Values.secrets.postgresDsn.version }}
      {{- end }}
  - secretKey: sa-key.json
    remoteRef:
      key: {{ .Values.secrets.serviceAccountKeyFile.key }}
      {{- if .Values.secrets.serviceAccountKeyFile.version }}
      version: {{ .Values.secrets.serviceAccountKeyFile.version }}
      {{- end }}
  
