/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { HubConnection, IStreamResult, Subject } from '@microsoft/signalr';
import type { IMainHub } from './WebSocketGateway.Web.Hubs';
import type { IClientReceiver } from './WebSocketGateway.Web.Receivers';


// components

export type Disposable = {
    dispose(): void;
}

export type HubProxyFactory<T> = {
    createHubProxy(connection: HubConnection): T;
}

export type ReceiverRegister<T> = {
    register(connection: HubConnection, receiver: T): Disposable;
}

type ReceiverMethod = {
    methodName: string,
    method: (...args: any[]) => void
}

class ReceiverMethodSubscription implements Disposable {

    public constructor(
        private connection: HubConnection,
        private receiverMethod: ReceiverMethod[]) {
    }

    public readonly dispose = () => {
        for (const it of this.receiverMethod) {
            this.connection.off(it.methodName, it.method);
        }
    }
}

// API

export type HubProxyFactoryProvider = {
    (hubType: "IMainHub"): HubProxyFactory<IMainHub>;
}

export const getHubProxyFactory = ((hubType: string) => {
    if(hubType === "IMainHub") {
        return IMainHub_HubProxyFactory.Instance;
    }
}) as HubProxyFactoryProvider;

export type ReceiverRegisterProvider = {
    (receiverType: "IClientReceiver"): ReceiverRegister<IClientReceiver>;
}

export const getReceiverRegister = ((receiverType: string) => {
    if(receiverType === "IClientReceiver") {
        return IClientReceiver_Binder.Instance;
    }
}) as ReceiverRegisterProvider;

// HubProxy

class IMainHub_HubProxyFactory implements HubProxyFactory<IMainHub> {
    public static Instance = new IMainHub_HubProxyFactory();

    private constructor() {
    }

    public readonly createHubProxy = (connection: HubConnection): IMainHub => {
        return new IMainHub_HubProxy(connection);
    }
}

class IMainHub_HubProxy implements IMainHub {

    public constructor(private connection: HubConnection) {
    }
}


// Receiver

class IClientReceiver_Binder implements ReceiverRegister<IClientReceiver> {

    public static Instance = new IClientReceiver_Binder();

    private constructor() {
    }

    public readonly register = (connection: HubConnection, receiver: IClientReceiver): Disposable => {

        const __onPublicationStatusChanged = (...args: [string, string, string, string]) => receiver.onPublicationStatusChanged(...args);
        const __onVideoEditingStepChanged = (...args: [string, string, string, string, string]) => receiver.onVideoEditingStepChanged(...args);
        const __onNodeExecutionStatusChanged = (...args: [string, string, any, string]) => receiver.onNodeExecutionStatusChanged(...args);

        connection.on("OnPublicationStatusChanged", __onPublicationStatusChanged);
        connection.on("OnVideoEditingStepChanged", __onVideoEditingStepChanged);
        connection.on("OnNodeExecutionStatusChanged", __onNodeExecutionStatusChanged);

        const methodList: ReceiverMethod[] = [
            { methodName: "OnPublicationStatusChanged", method: __onPublicationStatusChanged },
            { methodName: "OnVideoEditingStepChanged", method: __onVideoEditingStepChanged },
            { methodName: "OnNodeExecutionStatusChanged", method: __onNodeExecutionStatusChanged }
        ]

        return new ReceiverMethodSubscription(connection, methodList);
    }
}

