/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { IStreamResult, Subject } from '@microsoft/signalr';

export type IClientReceiver = {
    /**
    * @param publicationRecordId Transpiled from System.Guid
    * @param status Transpiled from string
    * @param publicUrl Transpiled from string?
    * @param error Transpiled from string?
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    onPublicationStatusChanged(publicationRecordId: string, status: string, publicUrl: string, error: string): Promise<void>;
    /**
    * @param videoId Transpiled from string
    * @param nodeId Transpiled from string
    * @param step Transpiled from string
    * @param status Transpiled from string
    * @param error Transpiled from string?
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    onVideoEditingStepChanged(videoId: string, nodeId: string, step: string, status: string, error: string): Promise<void>;
    /**
    * @param nodeId Transpiled from string
    * @param status Transpiled from string
    * @param outputs Transpiled from object?
    * @param error Transpiled from string?
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    onNodeExecutionStatusChanged(nodeId: string, status: string, outputs: any, error: string): Promise<void>;
    /**
    * @param jobId Transpiled from string
    * @param templateId Transpiled from string
    * @param mediaId Transpiled from string?
    * @param mediaType Transpiled from string?
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    onGraphCompleted(jobId: string, templateId: string, mediaId: string, mediaType: string): Promise<void>;
}

