name: "Telegram Notification Template"
description: "Sends message to Telegram topic"

inputs:
    message:
        required: true
        description: "Message to send"
    chat_id:
        required: true
        description: "Chat to send message to"
    topic_id:
        required: true
        description: "Topic to send message to"
    bot_token:
        required: true
        description: "Telegram Bot Token"

runs:
    using: "composite"
    steps:
        - name: Send Telegram Notification
          shell: bash
          run: |
              JSON_PAYLOAD=$(jq -n \
              --arg chat_id "${{ inputs.chat_id }}" \
              --arg thread_id "${{ inputs.topic_id }}" \
              --arg text "${{ inputs.message }}" \
              '{
                  chat_id: $chat_id,
                  message_thread_id: $thread_id,
                  text: $text,
                  parse_mode: "Markdown",
                  disable_web_page_preview: true
              }')

              curl -s -X POST "https://api.telegram.org/bot${{ inputs.bot_token }}/sendMessage" \
              -H "Content-Type: application/json" \
              -d "$JSON_PAYLOAD"
