apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
spec:
  {{- with .Values.virtualService.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        prefix: "/api/auth"
    route:
    - destination:
        host: "{{ include "user-service.fullname" . }}"
        port:
          number: {{ .Values.service.port }}
    timeout: {{ .Values.virtualService.http.timeout }}
    retries:
      attempts: {{ .Values.virtualService.http.retries.attempts }}
      perTryTimeout: {{ .Values.virtualService.http.retries.perTryTimeout }}
      retryOn: {{ .Values.virtualService.http.retries.retryOn }}