// <auto-generated/>
#pragma warning disable CS0618
using AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.ImportGs;
using AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.ImportUrl;
using AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item;
using AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.PresignedUpload;
using AiGateway.Web.Clients.MediaIngest.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace AiGateway.Web.Clients.MediaIngest.Api.Internal.Media
{
    /// <summary>
    /// Builds and executes requests for operations under \api\internal\media
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MediaRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The importGs property</summary>
        public global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.ImportGs.ImportGsRequestBuilder ImportGs
        {
            get => new global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.ImportGs.ImportGsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The importUrl property</summary>
        public global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.ImportUrl.ImportUrlRequestBuilder ImportUrl
        {
            get => new global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.ImportUrl.ImportUrlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The presignedUpload property</summary>
        public global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.PresignedUpload.PresignedUploadRequestBuilder PresignedUpload
        {
            get => new global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.PresignedUpload.PresignedUploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the AiGateway.Web.Clients.MediaIngest.api.internal.media.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item.WithMediaItemRequestBuilder"/></returns>
        public global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item.WithMediaItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("mediaId", position);
                return new global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.Item.WithMediaItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.MediaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MediaRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/internal/media", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.MediaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MediaRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/internal/media", rawUrl)
        {
        }
        /// <summary>
        /// Service-to-service only. Stores any file type without auth. Returns mediaId for use in subsequent requests.
        /// </summary>
        /// <returns>A <see cref="global::AiGateway.Web.Clients.MediaIngest.Models.UploadFileDto"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::AiGateway.Web.Clients.MediaIngest.Models.HttpValidationProblemDetails">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::AiGateway.Web.Clients.MediaIngest.Models.UploadFileDto?> PostAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::AiGateway.Web.Clients.MediaIngest.Models.UploadFileDto> PostAsync(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::AiGateway.Web.Clients.MediaIngest.Models.HttpValidationProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::AiGateway.Web.Clients.MediaIngest.Models.UploadFileDto>(requestInfo, global::AiGateway.Web.Clients.MediaIngest.Models.UploadFileDto.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Service-to-service only. Stores any file type without auth. Returns mediaId for use in subsequent requests.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(MultipartBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "multipart/form-data", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.MediaRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.MediaRequestBuilder WithUrl(string rawUrl)
        {
            return new global::AiGateway.Web.Clients.MediaIngest.Api.Internal.Media.MediaRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MediaRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
