// <auto-generated />
using System;
using MediaIngest.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaIngest.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260415142513_RefactorMediaVariantsToLinkedEntities")]
    partial class RefactorMediaVariantsToLinkedEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("media_ingest")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaIngest.Domain.Entities.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_key");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<Guid?>("ParentMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_media_id");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("integer")
                        .HasColumnName("processing_status");

                    b.Property<int?>("Variant")
                        .HasColumnType("integer")
                        .HasColumnName("variant");

                    b.HasKey("Id")
                        .HasName("pk_media_files");

                    b.HasIndex("ParentMediaId", "Variant")
                        .IsUnique()
                        .HasDatabaseName("ix_media_files_parent_media_id_variant")
                        .HasFilter("parent_media_id IS NOT NULL");

                    b.ToTable("media_files", "media_ingest");
                });

            modelBuilder.Entity("MediaIngest.Domain.Entities.MediaFile", b =>
                {
                    b.HasOne("MediaIngest.Domain.Entities.MediaFile", null)
                        .WithMany()
                        .HasForeignKey("ParentMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_media_files_media_files_parent_media_id");
                });
#pragma warning restore 612, 618
        }
    }
}
