// <auto-generated/>
#pragma warning disable CS0618
using AiGateway.Web.Clients.ElevenLabs.V1;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace AiGateway.Web.Clients.ElevenLabs
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ElevenLabsClient : BaseRequestBuilder
    {
        /// <summary>The v1 property</summary>
        public global::AiGateway.Web.Clients.ElevenLabs.V1.V1RequestBuilder V1
        {
            get => new global::AiGateway.Web.Clients.ElevenLabs.V1.V1RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::AiGateway.Web.Clients.ElevenLabs.ElevenLabsClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ElevenLabsClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
        }
    }
}
#pragma warning restore CS0618
