"use client";

import { useParams, useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { ImageIcon, Video, Loader2, PackageOpen } from "lucide-react";
import { ProjectHeader } from "@/components/ProjectHeader";
import { Button } from "@/components/ui/button";
import { useProjects } from "@/features/ambassadors/hooks/useProjects";
import { useProjectAssets } from "@/features/ambassadors/hooks/useProjectAssets";
import type { ProjectAsset } from "@/features/ambassadors/types";

function AssetCard({ asset, projectId }: { asset: ProjectAsset; projectId: string }) {
  const router = useRouter();
  const video = asset.mediaType === "Video";
  const date = new Date(asset.createdAt).toLocaleDateString(undefined, {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.97 }}
      animate={{ opacity: 1, scale: 1 }}
      onClick={() => router.push(`/projects/${projectId}/assets/${asset.id}`)}
      className="group relative rounded-xl overflow-hidden bg-card border border-border/50 hover:border-border transition-all cursor-pointer"
    >
      <div className="aspect-video bg-muted/40 relative flex items-center justify-center overflow-hidden">
        {video ? (
          <video
            src={asset.mediaUrl}
            className="w-full h-full object-cover"
            muted
            playsInline
            onMouseEnter={(e) => (e.currentTarget as HTMLVideoElement).play()}
            onMouseLeave={(e) => {
              const v = e.currentTarget as HTMLVideoElement;
              v.pause();
              v.currentTime = 0;
            }}
          />
        ) : (
          <img
            src={asset.mediaUrl}
            alt="Generated asset"
            className="w-full h-full object-cover"
          />
        )}

        {/* type badge */}
        <div className="absolute top-2 left-2 flex items-center gap-1 px-2 py-0.5 rounded-full bg-black/60 text-white text-xs font-medium backdrop-blur-sm">
          {video
            ? <><Video className="w-3 h-3" /> Video</>
            : <><ImageIcon className="w-3 h-3" /> Image</>
          }
        </div>
      </div>

      <div className="px-3 py-2 flex items-center justify-between">
        <span className="text-xs text-muted-foreground">{date}</span>
      </div>
    </motion.div>
  );
}

export default function AssetsPage() {
  const params = useParams();
  const projectId = params?.projectId as string;

  const { projects, isLoading: projectsLoading } = useProjects();
  const { assets, isLoading, error, nextCursor, loadMore } = useProjectAssets(projectId);

  return (
    <div className="min-h-screen bg-background">
      <ProjectHeader projects={projects} isLoading={projectsLoading} />

      <div className="container mx-auto px-6 py-8">
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <h1 className="text-2xl font-bold">Generated Assets</h1>
          <p className="text-muted-foreground text-sm mt-1">
            All media generated by your templates in this project.
          </p>
        </motion.div>

        {/* Loading skeleton */}
        {isLoading && assets.length === 0 && (
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
            {Array.from({ length: 8 }).map((_, i) => (
              <div key={i} className="aspect-video rounded-xl bg-muted/40 animate-pulse" />
            ))}
          </div>
        )}

        {/* Error */}
        {error && (
          <div className="text-center py-20 text-destructive">{error}</div>
        )}

        {/* Empty state */}
        {!isLoading && !error && assets.length === 0 && (
          <div className="flex flex-col items-center justify-center py-24 text-center gap-4">
            <div className="w-16 h-16 rounded-2xl bg-muted/40 flex items-center justify-center">
              <PackageOpen className="w-8 h-8 text-muted-foreground" />
            </div>
            <div>
              <p className="font-medium">No assets yet</p>
              <p className="text-sm text-muted-foreground mt-1">
                Run a template to generate your first asset.
              </p>
            </div>
          </div>
        )}

        {/* Grid */}
        {assets.length > 0 && (
          <>
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
              {assets.map((asset) => (
                <AssetCard key={asset.id} asset={asset} projectId={projectId} />
              ))}
            </div>

            {nextCursor && (
              <div className="mt-8 flex justify-center">
                <Button variant="outline" onClick={loadMore} disabled={isLoading}>
                  {isLoading ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : null}
                  Load more
                </Button>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
