secrets:
  postgresDsn:
    key: template-service-db-conn-test
  serviceAccountKeyFile:
    key: template-service-sa-key-test
  rabbitmqUrl:
    key: rabbitmq-test
  langfuseSecretKey:
    key: test-langfuse-secret-key
  langfusePublicKey:
    key: test-langfuse-public-key

config:
  mediaIngestUrl: "http://mediaingest.test-env.svc.cluster.local/media/api"
  gcpProjectId: "project-d72a81f9-0097-4b5b-a62"
  gcpLocation: "global"
  gcpStorageUri: "gs://amplify-media-test"
  userServiceUrl: "http://userservice.test-env.svc.cluster.local/userservice/api"
  videoEditorUrl: "http://video-editor.test-env.svc.cluster.local:8000"
  langfuseUrl: "https://cloud.langfuse.com"