apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: grafana-cloud-secret
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_CLOUD_API_KEY
      remoteRef:
        key: {{ .Values.observability.grafana.secretKey }}
    - secretKey: GRAFANA_CLOUD_INSTANCE_ID
      remoteRef:
        key: {{ .Values.observability.grafana.instanceIdKey }}