{{- if .Values.kiali.prometheus }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kiali-prometheus-auth
  namespace: istio-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: kiali-prometheus-auth
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.kiali.prometheus.secrets.usernameKey }}
    - secretKey: passphrase
      remoteRef:
        key: {{ .Values.kiali.prometheus.secrets.passwordKey }}
{{- end }}
