apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-external-secret-1
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: litellm-secret
    creationPolicy: Owner
  data:
    - secretKey: sa-key.json
      remoteRef:
        key: {{ .Values.litellm.secrets.serviceAccountKeyFile.key }}
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: {{ .Values.litellm.secrets.masterKey.key }}
    - secretKey: LANGFUSE_SECRET_KEY
      remoteRef:
        key: {{ .Values.litellm.secrets.langfuseSecretKey.key }}
    - secretKey: LANGFUSE_PUBLIC_KEY
      remoteRef:
        key: {{ .Values.litellm.secrets.langfusePublicKey.key }}
    - secretKey: DATABASE_USERNAME
      remoteRef:
        key: {{ .Values.litellm.secrets.databaseUsername.key }}
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: {{ .Values.litellm.secrets.databasePassword.key }}
    - secretKey: DATABASE_NAME
      remoteRef:
        key: {{ .Values.litellm.secrets.databaseName.key }}
    - secretKey: DATABASE_HOST
      remoteRef:
        key: {{ .Values.litellm.secrets.databaseHost.key }}
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: {{ .Values.litellm.secrets.openAiApiKey.key }}
    - secretKey: ELEVENLABS_API_KEY
      remoteRef:
        key: {{ .Values.litellm.secrets.elevenLabsApiKey.key }}
    - secretKey: RESEND_API_KEY
      remoteRef:
        key: {{ .Values.litellm.secrets.resendApiKey.key }}
