apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    {{- if (.Values.secretStore).fake }}
    fake:
      data:
        {{- toYaml .Values.secretStore.fakeData | nindent 8 }}
    {{- else }}
    gcpsm:
      projectID: project-d72a81f9-0097-4b5b-a62
      auth:
        workloadIdentity:
          clusterLocation: europe-west3-a
          clusterName: amplify-cluster
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
    {{- end }}
