/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { HubConnection, IStreamResult, Subject } from '@microsoft/signalr';
import type { IPublisherHub } from './Publisher.Infrastructure.Hubs';
import type { IPublisherReceiver } from './Publisher.Infrastructure.Receivers';


// components

export type Disposable = {
    dispose(): void;
}

export type HubProxyFactory<T> = {
    createHubProxy(connection: HubConnection): T;
}

export type ReceiverRegister<T> = {
    register(connection: HubConnection, receiver: T): Disposable;
}

type ReceiverMethod = {
    methodName: string,
    method: (...args: any[]) => void
}

class ReceiverMethodSubscription implements Disposable {

    public constructor(
        private connection: HubConnection,
        private receiverMethod: ReceiverMethod[]) {
    }

    public readonly dispose = () => {
        for (const it of this.receiverMethod) {
            this.connection.off(it.methodName, it.method);
        }
    }
}

// API

export type HubProxyFactoryProvider = {
    (hubType: "IPublisherHub"): HubProxyFactory<IPublisherHub>;
}

export const getHubProxyFactory = ((hubType: string) => {
    if(hubType === "IPublisherHub") {
        return IPublisherHub_HubProxyFactory.Instance;
    }
}) as HubProxyFactoryProvider;

export type ReceiverRegisterProvider = {
    (receiverType: "IPublisherReceiver"): ReceiverRegister<IPublisherReceiver>;
}

export const getReceiverRegister = ((receiverType: string) => {
    if(receiverType === "IPublisherReceiver") {
        return IPublisherReceiver_Binder.Instance;
    }
}) as ReceiverRegisterProvider;

// HubProxy

class IPublisherHub_HubProxyFactory implements HubProxyFactory<IPublisherHub> {
    public static Instance = new IPublisherHub_HubProxyFactory();

    private constructor() {
    }

    public readonly createHubProxy = (connection: HubConnection): IPublisherHub => {
        return new IPublisherHub_HubProxy(connection);
    }
}

class IPublisherHub_HubProxy implements IPublisherHub {

    public constructor(private connection: HubConnection) {
    }
}


// Receiver

class IPublisherReceiver_Binder implements ReceiverRegister<IPublisherReceiver> {

    public static Instance = new IPublisherReceiver_Binder();

    private constructor() {
    }

    public readonly register = (connection: HubConnection, receiver: IPublisherReceiver): Disposable => {

        const __onPublicationStatusChanged = (...args: [string, string, string, string]) => receiver.onPublicationStatusChanged(...args);

        connection.on("OnPublicationStatusChanged", __onPublicationStatusChanged);

        const methodList: ReceiverMethod[] = [
            { methodName: "OnPublicationStatusChanged", method: __onPublicationStatusChanged }
        ]

        return new ReceiverMethodSubscription(connection, methodList);
    }
}

